
spring:
  application:
    name: employee-service

  datasource:
    url: jdbc:mysql://localhost:3306/peopleinfo
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8082
  servlet:
    context-path: /employee


